title: 'Procesadores de Lenguajes'
subtitle: 'Itinerario de Computación. Grado en Ingeniería Informática. ULL. Curso 2018/2019'
theme: jekyll-theme-midnight
description: '3º. 2º cuatrimestre. Itinerario de Computación. Grado en Ingeniería Informática. ULL'
acronym: PL
exclude: [ 'Arona-winter-course', 'dsi1819', 'dsi1819-introduccion', 'tema0-introduccion-a-pl/practicas/code']
baseurl: '/introduccion'
url: https://ULL-ESIT-PL-1819.github.io/introduccion
show_downloads: false
calendario_academico: https://www.ull.es/estudios-docencia/calendario-academico/
horarios_examenes: https://www.ull.es/grados/ingenieria-informatica/informacion-academica/horarios-y-calendario-examenes/
calendario_examenes: https://docs.google.com/document/d/1j5rJyULD1c42UV4o-g85puuPlbO-DNFmaobn_vnKgKw/edit#
horarios_tutorias: https://docs.google.com/spreadsheets/d/1ZTGvLA70qCYEsBwcA8dCiUZby3ZOM9oHt8kmiNNKId0/edit#gid=0
google_plus: https://plus.google.com/u/1/communities/101901734024125937720
organization: 
  url: https://github.com/ULL-ESIT-PL-1920/introduccion
  name: ULL-ESIT-PL-1920
  master: https://github.com/ULL-ESIT-PL-1819/introduccion/tree/master/
apuntes_repo: https://github.com/ULL-ESIT-PL-1819/introduccion/
campus_virtual: https://campusvirtual.ull.es/1920/course/view.php?id=201911070
calificador: https://campusvirtual.ull.es/1920/grade/report/grader/index.php?id=201911070
tareas: https://campusvirtual.ull.es/1920/mod/assign/index.php?id=201911070
profesor: https://www.ull.es/apps/guias/guias/view_teacher_niu/588/(%3FPcrguezl.*)/
profesor_github: crguezl
bull_permanente: https://puntoq.ull.es/permalink/f
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: https://classroom.github.com/classrooms/53047670-ull-esit-pl-1920
  name: ULL-ESIT-PL-1920
temas:
  - title: 'Tema 0: Introducción a la Asignatura'
    url: /tema0-introduccion-a-pl/guia-docente.html
    hover: 'Presentación'
  - title: 'Tema 1: Introducción a JavaScript'
    url: /tema1-introduccion-a-javascript/
    hover: 'Intro-a-js'
  - title: 'Tema 2: Expresiones Regulares y Análisis Léxico'
    url: /tema2-expresiones-regulares-y-analisis-lexico/
    hover: 'tema2-expresiones-regulares-y-analisis-lexico'
  - title: 'Análisis Sintactico Descendente Recursivo Predictivo'
    url: /tema3-analisis-descendente-predictivo-recursivo/
    hover: 'tema3-pdr'
practicas:
  - title: 00cuestionarioghalu
    myurl: https://campusvirtual.ull.es/1920/mod/assign/view.php?id=14658
    name: Tarea Formulario Usuario de Github
  - title: 01comunidadgpluspl
    myurl: https://campusvirtual.ull.es/1920/mod/assign/view.php?id=14657
    name: Tarea Comunidad G+ de PL
  - title: 02pb-gh-campus-expert
    myurl: /tema0-introduccion-a-pl/practicas/pb-gh-campus-expert/
    name: Práctica pb-gh-campus-expert
  - title: 03p0-t0-esprima-logging
    myurl: /tema0-introduccion-a-pl/practicas/p0-t0-esprima-logging
    name: Práctica p0-t0-esprima-logging
    reto:
      title: Funciones Flecha Gorda y Nº de línea
      url: /tema0-introduccion-a-pl/practicas/p0-t0-esprima-logging-reto
  - title: 04p1-t1-iaas
    myurl: /tema1-introduccion-a-javascript/practicas/p1-t1-iaas/
    name: Práctica p1-t1-iaas
    reto: 
      url: /tema1-introduccion-a-javascript/practicas/p1-t1-iaas/reto-async
      title: Reto Async Map
  - title: 05p2-t1-vscode
    myurl: /tema1-introduccion-a-javascript/practicas/p2-t1-vscode/
    name: Práctica p2-t1-vscode
  - title: 06p3-t1-handling-events
    myurl: /tema1-introduccion-a-javascript/practicas/p3-t1-handling-events/
    name: Práctica p3-t1-handling-events
    reto: 
      url: /tema1-introduccion-a-javascript/practicas/p3-t1-handling-events/reto
      title: Reto Async Serialize
  - title: 07p2-t1-testing
    myurl: /tema1-introduccion-a-javascript/practicas/p2-t1-testing/
    name: Práctica p2-t1-testing
    reto: 
      url: /tema1-introduccion-a-javascript/practicas/p2-t1-testing//reto
      title: Reto Webpages for Authors
  - title: 08p3-t2-regexp
    myurl: /tema2-expresiones-regulares-y-analisis-lexico/practicas/p3-t2-regexp/reto
    name: Práctica p3-t2-regexp
  - title: 09p9-t2-lexer
    myurl: /tema2-expresiones-regulares-y-analisis-lexico/practicas/p9-t2-lexer/
    name: Práctica p9-t2-lexer
    reto: 
      url: /tema2-expresiones-regulares-y-analisis-lexico/practicas/p9-t2-lexer/reto-ini
      title: Reto Parse INI Files
  - title: 10p10-t2-lexer-generator
    myurl: /tema2-expresiones-regulares-y-analisis-lexico/practicas/p10-t2-lexer-generator/
    name: Práctica p10-t2-lexer-generator
    reto:
      url: /tema2-expresiones-regulares-y-analisis-lexico/practicas/p10-t2-lexer-generator/reto
      title: Reto Hello Actions!
  - title: 11p5-t1-egg-0
    myurl: /tema3-analisis-descendente-predictivo-recursivo/practicas/p5-t3-egg-0/
    name: Práctica p5-t1-egg-0
    reto:
      url: /tema3-analisis-descendente-predictivo-recursivo/practicas/p5-t3-egg-0/retos
      title: Reto Parenthesis, Mocking and Stubbing
  - title: 12p6-t3-egg-1
    myurl: /tema3-analisis-descendente-predictivo-recursivo/practicas/p6-t3-egg-1/
    name: Práctica p6-t3-egg-1
  - title: 13p7-t3-egg-1
    myurl: /tema3-analisis-descendente-predictivo-recursivo/practicas/p7-t3-egg-2/
    name: Práctica p7-t3-egg-2
  - title: 14p8-t3-pdr-infix2egg
    myurl: /tema3-analisis-descendente-predictivo-recursivo/practicas/p8-t3-pdr-infix2egg/
    name: Práctica p8-t3-pdr-infix2egg
    

